/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.12
 * Generated at: 2014-09-26 12:45:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/home/golf/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Profile/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1364130896000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

	Class.forName("com.mysql.jdbc.Driver");

      out.write('\n');
      out.write('\n');

	Connection connection = DriverManager.getConnection(
			"jdbc:mysql://localhost:3306/Myprofile", "root", "3009");

	Statement st = connection.createStatement();
	String obj = "All";
	session = request.getSession();
	if(null != session.getAttribute("job")){
		obj = (String)session.getAttribute("job");
	}
	

	ResultSet rs;
	if (obj.equals("All")) {
		rs = st.executeQuery("select * from user");
	} else if (obj.equals("Manager")) {
		rs = st.executeQuery("select * from user where job = 'Manager'");
	} else {
		rs = st.executeQuery("select * from user where job = 'Employee'");
	}

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref='");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("'>\n");
      out.write("<title>Admin Page</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<div id=\"register\">\n");
      out.write("\t\t<div class=\"header\">\n");
      out.write("\t\t\t<a class=\"logo\">Manage user</a> <a class=\"Login\" href=\"/Profile/\">Logout</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"regis\">\n");
      out.write("\t\t\t<h> Manage user</h>\n");
      out.write("\n");
      out.write("\t\t\t<form name=\"form\" method=\"POST\" action=\"Admin\">\n");
      out.write("\t\t\t\t<TABLE BORDER=\"1\">\n");
      out.write("\t\t\t\t<!--  \t<select id=\"map\" name=\"map\" onchange=\"Assign()\">\n");
      out.write("\t\t\t\t\t\t<option value=\"All\">All</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"Manager\">Manager</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"Employee\">Employee</option>  \n");
      out.write("\t\t\t\t\t</select>  -->\n");
      out.write("\t\t\t\t\t<input type=\"button\" id = \"job1\" value=\"All\" onClick=\"Assign1()\" />\n");
      out.write("\t\t\t\t\t<input type=\"button\" id = \"job2\" value=\"Manager\" onClick=\"Assign2()\" />\n");
      out.write("\t\t\t\t\t<input type=\"button\" id = \"job3\" value=\"Employee\" onClick=\"Assign3()\" />\n");
      out.write("\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t<TR>\n");
      out.write("\t\t\t\t\t\t<TH>ID</TH>\n");
      out.write("\t\t\t\t\t\t<TH>First name</TH>\n");
      out.write("\t\t\t\t\t\t<TH>Last name</TH>\n");
      out.write("\t\t\t\t\t\t<TH>About</TH>\n");
      out.write("\t\t\t\t\t\t<TH>Location</TH>\n");
      out.write("\t\t\t\t\t\t<TH>Contact</TH>\n");
      out.write("\t\t\t\t\t\t<TH>Education</TH>\n");
      out.write("\t\t\t\t\t\t<TH>Job</TH>\n");
      out.write("\t\t\t\t\t</TR>\n");
      out.write("\t\t\t\t\t");

						while (rs.next()) {
					
      out.write("\n");
      out.write("\t\t\t\t\t<TR>\n");
      out.write("\t\t\t\t\t\t<TD>");
      out.print(rs.getString(1));
      out.write("</TD>\n");
      out.write("\t\t\t\t\t\t<TD>");
      out.print(rs.getString(4));
      out.write("</TD>\n");
      out.write("\t\t\t\t\t\t<TD>");
      out.print(rs.getString(5));
      out.write("</TD>\n");
      out.write("\t\t\t\t\t\t<TD>");
      out.print(rs.getString(6));
      out.write("</TD>\n");
      out.write("\t\t\t\t\t\t<TD>");
      out.print(rs.getString(7));
      out.write("</TD>\n");
      out.write("\t\t\t\t\t\t<TD>");
      out.print(rs.getString(8));
      out.write("</TD>\n");
      out.write("\t\t\t\t\t\t<TD>");
      out.print(rs.getString(9));
      out.write("</TD>\n");
      out.write("\t\t\t\t\t\t<TD><select name=\"jobs\">\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"");
      out.print(rs.getString(1) + "-None");
      out.write("\">None</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"");
      out.print(rs.getString(1) + "-Manager");
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\t");
if ("Manager".equals(rs.getString(10)))
					out.print("selected");
      out.write(">Manager</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"");
      out.print(rs.getString(1) + "-Employee");
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\t");
if ("Employee".equals(rs.getString(10)))
					out.print("selected");
      out.write(">Employee</option>\n");
      out.write("\t\t\t\t\t\t</select></TD>\n");
      out.write("\t\t\t\t\t</TR>\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\n");
      out.write("\t\t\t\t</TABLE>\n");
      out.write("\t\t\t\t<br> <input type=\"submit\" value=\"Save\" size=\"7\" />\n");
      out.write("\n");
      out.write("\t\t\t</form>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function Assign1(){\n");
      out.write("\twindow.location.href=\"/Profile/admin?map=\"+document.getElementById(\"job1\").value;\n");
      out.write("}\n");
      out.write("function Assign2(){\n");
      out.write("\twindow.location.href=\"/Profile/admin?map=\"+document.getElementById(\"job2\").value;\n");
      out.write("}\n");
      out.write("function Assign3(){\n");
      out.write("\twindow.location.href=\"/Profile/admin?map=\"+document.getElementById(\"job3\").value;\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/jsp/admin.jsp(32,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/resources/css/admin.css");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }
}
